version: '3.1'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ecommerce